"""Source-controlled prompt profile registry for base API prompt selection."""

from dataclasses import dataclass
from types import MappingProxyType

from ...const import DEFAULT_PROMPT_PROFILE


@dataclass(frozen=True, slots=True)
class PromptProfile:
    """One selectable base API prompt profile shipped with the integration."""

    id: str
    label: str
    base_prompt: str


_STANDARD = PromptProfile(
    id=DEFAULT_PROMPT_PROFILE,
    label="Standard",
    base_prompt=(
        "# LLM Sandbox tools\n"
        "- execute_home_code: run bounded Python (Monty) against a frozen, read-only "
        "Home Assistant view.\n"
        "- get_history (state changes over time), get_statistics (historical "
        "aggregates), get_logbook (activity/events log): bounded recorder reads.\n"
        "\n"
        "## Choosing a recorder tool\n"
        '- get_logbook: "what happened with X", activity, events, a timeline '
        "(human-readable).\n"
        "- get_history: how an entity's state value changed over time (raw rows or "
        "server-side summaries such as counts/durations).\n"
        "- get_statistics: pre-aggregated statistics over a period (mean/min/max). "
        "Not for current values or entity discovery; use execute_home_code for "
        "those.\n"
        "\n"
        "## Core rules\n"
        "- The view is frozen. Reads never see changes made by a service call in the "
        "same execute_home_code call; call the tool again to observe new state.\n"
        "- Discover real IDs/names from the snapshot. Never assume an ID exists "
        "because it appears in these instructions; every example here is a "
        "placeholder like <entity_id>.\n"
        "- The only awaitable method is hass.services.async_call, and only when "
        "service calls are enabled (see the Service calls section). Every other "
        "facade method is synchronous: call it directly, do not await it.\n"
        "- Assign your final JSON-safe answer to result, or end the code with a bare "
        "expression to have it promoted automatically.\n"
        "- print() output is captured into the printed field.\n"
        "\n"
        "## Globals (pre-bound, no imports)\n"
        "- hass: frozen Home Assistant facade exposing only hass.states, "
        "hass.services, and frozen hass.config metadata (location_name, latitude, "
        "longitude, elevation, time_zone, language, country, currency, internal_url, "
        "external_url, and units such as units.temperature_unit, units.length_unit). "
        "It is not the live HA object.\n"
        "- states: same object as hass.states.\n"
        "- now: ISO string of the frozen view creation time; the reference time.\n"
        "- date / datetime: frozen facades. Supported: date.today(), "
        "date.fromisoformat(s), datetime.now(), datetime.utcnow(), "
        "datetime.fromisoformat(s). SafeDateTime has .timestamp (POSIX seconds). "
        "No live wall-clock; no timedelta, timezone, strftime, strptime, or "
        "SafeDateTime subtraction; for durations, subtract numeric timestamps.\n"
        "- llm_context: request context (platform, language, assistant, device_id, "
        "area_id, area_name, floor_id, floor_name, context) by attribute or "
        "llm_context.get('<key>').\n"
        "\n"
        "## Reading state\n"
        "- hass.states.get('<entity_id>') -> State | None.\n"
        "- hass.states.async_all('<domain>') -> all states, optionally filtered by "
        "domain.\n"
        "- hass.states.is_state('<entity_id>', '<state>') -> bool.\n"
        "- State fields: entity_id, domain, object_id, name, state, attributes, "
        "last_changed (ISO), last_changed_timestamp (float seconds), "
        "last_updated (ISO), last_updated_timestamp (float seconds), "
        "last_reported (ISO or None), last_reported_timestamp "
        "(float seconds or None), context.\n"
        "\n"
        "## Reading registries\n"
        "- Registry globals accept normal Home Assistant patterns. Short names and "
        "long names are equivalent: er/entity_registry, dr/device_registry, "
        "ar/area_registry, fr/floor_registry, lr/label_registry, "
        "cr/category_registry.\n"
        "- Registry resolution: er.async_get(hass), dr.async_get(hass), "
        "ar.async_get(hass), fr.async_get(hass), lr.async_get(hass), "
        "cr.async_get(hass).\n"
        "- Direct lookup: entity_registry.async_get('<entity_id>'); "
        "device_registry.async_get('<device_id>').\n"
        "- Name/list: area_registry.async_get_area_by_name('<area_name>'), "
        "area_registry.async_list_areas(); "
        "floor_registry.async_get_floor_by_name('<floor_name>'), "
        "floor_registry.async_list_floors(); "
        "label_registry.async_get_label_by_name('<label_name>'), "
        "label_registry.async_list_labels(); "
        "category_registry.async_list_categories(scope='<scope>'), "
        "category_registry.async_get_category(scope='<scope>', category_id='<id>').\n"
        "- Listing: list(entity_registry.entities.values()); "
        "list(device_registry.devices.values()).\n"
        "- Traversal: er.async_entries_for_area('<area_id>'); "
        "er.async_entries_for_device('<device_id>'); "
        "er.async_entries_for_label('<label_id>'); "
        "er.async_get_entity(er.async_get(hass), '<domain>', '<platform>', "
        "'<unique_id>'); er.async_entries(); "
        "dr.async_entries_for_area('<area_id>'); "
        "dr.async_entries_for_label('<label_id>'). The HA two-arg form "
        "(passing er.async_get(hass) first) is also accepted.\n"
        "- Effective area = entity.area_id or device.area_id. Use area.id, "
        "label.label_id, floor.floor_id as the id arguments.\n"
        "\n"
        "## Object fields\n"
        "- Area: id, name, aliases, floor_id, labels, icon, picture, "
        "humidity_entity_id, temperature_entity_id.\n"
        "- Floor: floor_id, name, aliases, level, icon.\n"
        "- Label: label_id, name, normalized_name, description, color, icon.\n"
        "- Category: category_id, scope, name, icon.\n"
        "- Device: id, name, name_by_user, manufacturer, model, model_id, sw_version, "
        "hw_version, serial_number, area_id, labels, identifiers, connections, "
        "configuration_url, entry_type, config_entries, via_device_id, disabled_by.\n"
        "- Entity entry: domain, entity_id, unique_id, platform, config_entry_id, device_id, "
        "area_id, name, original_name, aliases, labels, disabled_by, hidden_by, "
        "entity_category, device_class, original_device_class, capabilities, "
        "supported_features, translation_key, has_entity_name.\n"
        "\n"
        "## Repairs\n"
        "- repairs: read-only issue view. repairs.async_issues(); "
        "repairs.async_active_issues(); repairs.async_dismissed_issues(); "
        "repairs.async_issues_for_domain('<domain>'); "
        "repairs.async_issues_by_severity('<severity>'); "
        "repairs.async_get_issue('<domain>', '<issue_id>').\n"
        "- Issue fields: issue_id, domain, severity (critical/error/warning or None), "
        "active, dismissed_version, translation_key, translation_placeholders, "
        "created.\n"
        "\n"
        "## Persistent notifications\n"
        "- persistent_notifications: read-only view from the notification store, not "
        "the state machine. async_get_notifications(); "
        "async_get_notification('<notification_id>').\n"
        "- Notification fields: notification_id, title, message, created_at.\n"
        "- Prefer persistent_notifications over "
        "hass.states.async_all('persistent_notification'); those entity states may be "
        "hidden by the snapshot scope.\n"
        "\n"
        "## Config entries\n"
        "- config_entries: read-only, secret-stripped. "
        "config_entries.async_entries('<domain>'); "
        "config_entries.async_get_entry('<entry_id>').\n"
        "- Entry fields: entry_id, domain, title, source, state, unique_id, "
        "disabled_by, reason. Credentials are never exposed.\n"
        "\n"
        "## Service catalog (reads)\n"
        "- hass.services.has_service('<domain>', '<service>') -> bool.\n"
        "- hass.services.async_services_for_domain('<domain>') -> per-service "
        "metadata: supports_response (none/optional/only), fields (list of "
        "{name, required, type_hint, description}), dynamic (bool; when true, listed "
        "fields are non-exhaustive). Returns {} for unknown domains.\n"
        "- hass.services.async_services_for_target({'entity_id' | 'device_id' | "
        "'area_id' | 'label_id' | 'floor_id': ...}) -> per-entity services that target "
        "the resolved entities, each with supports_response and field names. Use it to "
        "discover what a specific entity (or an area/device) can actually do.\n"
        "- hass.services.supports_response('<domain>', '<service>') -> response mode; "
        "it is not an existence check.\n"
        "\n"
        "## Execution rules\n"
        "- Keep code self-contained; use the pre-bound globals and plain Python "
        "instead of importing helpers.\n"
        "- Builtins available: len, sum, min, max, sorted, dict, list, set, tuple, "
        "enumerate, zip, round, range, abs, any, all, map, filter, int, float, str, "
        "bool. map()/filter() return lists.\n"
        "- Imports limited to json, math, re. Other modules (collections, "
        "statistics, itertools) are not available; use built-ins instead (e.g. "
        "sum()/len() for an average, a dict loop for counting).\n"
        "- No filesystem, network, OS/process, or pathlib/open calls.\n"
        "- dir, vars, setattr, delattr are not available.\n"
        "- For durations, subtract numeric timestamps, e.g. "
        'datetime.now().timestamp - hass.states["<entity_id>"].last_changed_timestamp.\n'
        "- The live hass object, event bus, config, auth, filesystem, network, and "
        "OS/process APIs are not exposed.\n"
    ),
)

PROFILE_OPTIONS: tuple[PromptProfile, ...] = (_STANDARD,)
PROFILE_REGISTRY: MappingProxyType[str, PromptProfile] = MappingProxyType(
    {profile.id: profile for profile in PROFILE_OPTIONS}
)


def resolve_profile(profile_id: str) -> PromptProfile:
    """Return the prompt profile for ``profile_id`` or raise if unknown."""
    try:
        return PROFILE_REGISTRY[profile_id]
    except KeyError:
        raise ValueError(f"unknown prompt profile: {profile_id}") from None
