"""Static LLM-facing prompts for the LLM Sandbox facade runtime.

This module is the single home for prose that is sent to the model and that
does not depend on runtime state. Runtime composition (conditional sections)
stays in ``api.py`` next to the state it renders from.
"""

BASE_API_PROMPT = (
    "# LLM Sandbox tools\n"
    "- execute_home_code: run bounded Python (Monty) against a frozen, read-only "
    "Home Assistant view.\n"
    "- get_history, get_statistics, get_logbook: bounded recorder reads "
    "(entity history, long-term statistics, logbook events).\n"
    "\n"
    "## Core rules\n"
    "- The view is frozen. Reads never see changes made by a service call in the "
    "same execute_home_code call; call the tool again to observe new state.\n"
    "- Discover real IDs/names from the snapshot. Never assume an ID exists "
    "because it appears in these instructions; every example here is a "
    "placeholder like <entity_id>.\n"
    "- The only awaitable method is hass.services.async_call, and only when "
    "service calls are enabled (see the Service calls section). Every other "
    "facade method is synchronous: call it directly, do not await it.\n"
    "- Assign your final JSON-safe answer to result, or end the code with a bare "
    "expression to have it promoted automatically.\n"
    "- print() output is captured into the printed field.\n"
    "\n"
    "## Globals (pre-bound, no imports)\n"
    "- hass: frozen Home Assistant facade exposing only hass.states, "
    "hass.services, and frozen hass.config metadata (location_name, latitude, "
    "longitude, elevation, time_zone, language, country, currency, internal_url, "
    "external_url, and units such as units.temperature_unit, units.length_unit). "
    "It is not the live HA object.\n"
    "- states: same object as hass.states.\n"
    "- now: ISO string of the frozen view creation time; the reference time.\n"
    "- date / datetime: frozen facades. Supported: date.today(), "
    "date.fromisoformat(s), datetime.now(), datetime.utcnow(), "
    "datetime.fromisoformat(s). No live wall-clock; no timedelta, timezone, "
    "strftime, strptime, or datetime arithmetic.\n"
    "- llm_context: request context (platform, language, assistant, device_id, "
    "area_id, area_name, floor_id, floor_name, context).\n"
    "\n"
    "## Reading state\n"
    "- hass.states.get('<entity_id>') -> State | None.\n"
    "- hass.states.async_all('<domain>') -> all states, optionally filtered by "
    "domain.\n"
    "- hass.states.is_state('<entity_id>', '<state>') -> bool.\n"
    "- State fields: entity_id, domain, object_id, name, state, attributes, "
    "last_changed (ISO), last_updated (ISO), last_reported (ISO or None), "
    "context.\n"
    "\n"
    "## Reading registries (mix by capability, not by style)\n"
    "Instance facades - use directly, no hass: entity_registry, device_registry, "
    "area_registry, floor_registry, label_registry, category_registry.\n"
    "- Direct lookup: entity_registry.async_get('<entity_id>'); "
    "device_registry.async_get('<device_id>').\n"
    "- Name/list (instance only): "
    "area_registry.async_get_area_by_name('<area_name>'), "
    "area_registry.async_list_areas(); "
    "floor_registry.async_get_floor_by_name('<floor_name>'), "
    "floor_registry.async_list_floors(); "
    "label_registry.async_get_label_by_name('<label_name>'), "
    "label_registry.async_list_labels(); "
    "category_registry.async_list_categories(scope='<scope>'), "
    "category_registry.async_get_category(scope='<scope>', "
    "category_id='<id>').\n"
    "- Listing: list(entity_registry.entities.values()); "
    "list(device_registry.devices.values()).\n"
    "Module facades - take hass via async_get: er, dr, ar, fr, lr, cr.\n"
    "- er/dr expose traversal helpers (pass the resolved registry as the first "
    "arg): er.async_entries_for_area(er.async_get(hass), '<area_id>'); "
    "er.async_entries_for_device(er.async_get(hass), '<device_id>'); "
    "er.async_entries_for_label(er.async_get(hass), '<label_id>'); "
    "er.async_get_entity(er.async_get(hass), '<domain>', '<platform>', "
    "'<unique_id>'); er.async_entries(er.async_get(hass)); "
    "dr.async_entries_for_area(dr.async_get(hass), '<area_id>'); "
    "dr.async_entries_for_label(dr.async_get(hass), '<label_id>').\n"
    "- ar/fr/lr/cr expose only async_get(hass).\n"
    "- Effective area = entity.area_id or device.area_id. Use area.id, "
    "label.label_id, floor.floor_id as the id arguments.\n"
    "\n"
    "## Object fields\n"
    "- Area: id, name, aliases, floor_id, labels, icon, picture, "
    "humidity_entity_id, temperature_entity_id.\n"
    "- Floor: floor_id, name, aliases, level, icon.\n"
    "- Label: label_id, name, normalized_name, description, color, icon.\n"
    "- Category: category_id, scope, name, icon.\n"
    "- Device: id, name, name_by_user, manufacturer, model, model_id, sw_version, "
    "hw_version, serial_number, area_id, labels, identifiers, connections, "
    "configuration_url, entry_type, config_entries, via_device_id, disabled_by.\n"
    "- Entity entry: entity_id, unique_id, platform, config_entry_id, device_id, "
    "area_id, name, original_name, aliases, labels, disabled_by, hidden_by, "
    "entity_category, device_class, original_device_class, capabilities, "
    "supported_features, translation_key, has_entity_name.\n"
    "\n"
    "## Repairs\n"
    "- repairs: read-only issue view. repairs.async_issues(); "
    "repairs.async_active_issues(); repairs.async_dismissed_issues(); "
    "repairs.async_issues_for_domain('<domain>'); "
    "repairs.async_issues_by_severity('<severity>'); "
    "repairs.async_get_issue('<domain>', '<issue_id>').\n"
    "- Issue fields: issue_id, domain, severity (critical/error/warning or None), "
    "active, dismissed_version, translation_key, translation_placeholders, "
    "created.\n"
    "\n"
    "## Persistent notifications\n"
    "- persistent_notifications: read-only view from the notification store, not "
    "the state machine. async_get_notifications(); "
    "async_get_notification('<notification_id>').\n"
    "- Notification fields: notification_id, title, message, created_at.\n"
    "- Prefer persistent_notifications over "
    "hass.states.async_all('persistent_notification'); those entity states may be "
    "hidden by the snapshot scope.\n"
    "\n"
    "## Config entries\n"
    "- config_entries: read-only, secret-stripped. "
    "config_entries.async_entries('<domain>'); "
    "config_entries.async_get_entry('<entry_id>').\n"
    "- Entry fields: entry_id, domain, title, source, state, unique_id, "
    "disabled_by, reason. Credentials are never exposed.\n"
    "\n"
    "## Service catalog (reads)\n"
    "- hass.services.has_service('<domain>', '<service>') -> bool.\n"
    "- hass.services.async_services_for_domain('<domain>') -> per-service "
    "metadata: supports_response (none/optional/only), fields (list of "
    "{name, required, type_hint, description}), dynamic (bool; when true, listed "
    "fields are non-exhaustive). Returns {} for unknown domains.\n"
    "- hass.services.supports_response('<domain>', '<service>') -> response mode; "
    "it is not an existence check.\n"
    "\n"
    "## Execution rules\n"
    "- Keep code self-contained; use the pre-bound globals and plain Python "
    "instead of importing helpers.\n"
    "- Builtins available: len, sum, min, max, sorted, dict, list, set, tuple, "
    "enumerate, zip, round, range, abs, any, all, map, filter, int, float, str, "
    "bool, bytes.\n"
    "- Imports limited to json, math, re. Do not import collections "
    "(Counter/defaultdict unavailable); count with a dict loop: "
    "counts[k] = counts.get(k, 0) + 1.\n"
    "- No filesystem, network, OS/process, or pathlib/open calls.\n"
    "- dir, vars, setattr, delattr are not available.\n"
    "- Timestamps (State.last_changed, etc.) are ISO strings; compare directly or "
    "parse with datetime.fromisoformat().\n"
    "- The live hass object, event bus, config, auth, filesystem, network, and "
    "OS/process APIs are not exposed.\n"
)


ACTIONS_ENABLED_PROMPT = (
    "## Service calls (enabled)\n"
    "- await hass.services.async_call('<domain>', '<service>', service_data, "
    "target={'entity_id': '<entity_id>'}, blocking=True) performs the call for "
    "real.\n"
    "- Keep service data and target separate; put entities in target "
    "(entity_id/device_id/area_id/label_id/floor_id).\n"
    "- blocking=True waits and reports outcome; blocking=False is "
    "fire-and-forget and yields no detailed error. Prefer blocking when you need "
    "to know it succeeded.\n"
    "- return_response=True requires blocking=True and is needed for services "
    "that produce a response.\n"
    "- Calls run sequentially with no rollback; a later failure does not undo "
    "earlier calls.\n"
    "- Each async_call costs one helper call; reads cost zero. Respect the "
    "budget.\n"
    "- Errors are returned as helper_error. If the service name is wrong, the "
    "response lists valid services for the domain with brief schemas; correct and "
    "retry.\n"
)


ACTIONS_DISABLED_PROMPT = (
    "## Service calls (disabled)\n"
    "Service calls are disabled for this assistant. hass.services.async_call is "
    "rejected. Use the service-catalog reads (has_service, "
    "async_services_for_domain, supports_response), states, and registries "
    "only.\n"
)


def build_execute_home_code_description() -> str:
    """Return the execute_home_code tool description."""
    return (
        "Execute bounded Python/Monty code against a frozen, read-only Home Assistant view. "
        "Read states and registries using the native Home Assistant patterns documented in the API prompt. "
        "Service-call availability follows the API prompt. "
        "Returns {execution, output, printed, actions}. execution.status is "
        "ok | code_error | helper_error | setup_error; use output only when status is ok. "
        "printed holds captured print() lines. actions lists service calls with status, "
        "response, and error details."
    )


def build_get_history_description() -> str:
    """Return the get_history tool description."""
    return (
        "Return recorded state history for visible entities over a bounded UTC window. "
        "Returns {status, window, entities, truncated}."
    )


def build_get_statistics_description() -> str:
    """Return the get_statistics tool description."""
    return (
        "Return long-term recorder statistics for visible statistic IDs over a bounded UTC window. "
        "Each statistic ID must be a currently-visible entity ID; external or non-entity "
        "statistic IDs are rejected. "
        "Returns {status, window, period, statistics, truncated}. Units are raw recorder units."
    )


def build_get_logbook_description() -> str:
    """Return the get_logbook tool description."""
    return (
        "Return logbook events for visible entities over a bounded UTC window. "
        "Returns {status, window, entries, truncated}."
    )
