"""Static LLM-facing prompts for the LLM Sandbox facade runtime.

This module is the single home for prose that is sent to the model and that
does not depend on runtime state. Runtime composition (conditional sections)
stays in ``api.py`` next to the state it renders from.
"""

BASE_API_PROMPT = (
    "## Tools\n"
    "LLM Sandbox exposes one tool: execute_home_code. It runs bounded "
    "Python/Monty against a frozen read-only view of your Home Assistant.\n"
    "\n"
    "## Globals\n"
    "The following globals are pre-bound (no imports needed):\n"
    "- hass: the Home Assistant root. Exposes hass.states (StateMachine) and "
    "hass.services (service catalog + async_call), and hass.config. "
    "hass.config exposes frozen instance metadata: location_name, latitude, "
    "longitude, elevation, time_zone, language, country, currency, "
    "internal_url, external_url, and units such as units.temperature_unit and "
    "units.length_unit.\n"
    "- states: hass.states (same object). Read entity state.\n"
    "- er, dr, ar, fr: module facades. Pass hass only to these facades: "
    "er.async_get(hass), dr.async_get(hass), ar.async_get(hass), and "
    "fr.async_get(hass) return registry instances.\n"
    "- entity_registry, device_registry, area_registry, floor_registry: the "
    "already-resolved registry instances. Do not call async_get(hass) on these "
    "globals; their methods take entity IDs, device IDs, area IDs, floor IDs, "
    "or names, not hass.\n"
    "- now: the frozen view creation time as an ISO string. Use it as the "
    "reference time for comparisons with State timestamp strings.\n"
    "- llm_context: the current request context (platform, language, assistant, "
    "device_id, area_id, area_name, floor_id, floor_name, context).\n"
    "\n"
    "## Reading state\n"
    "- hass.states.get('light.bedroom') returns the State or None.\n"
    "- hass.states.async_all() returns all states; pass a domain string to "
    "filter.\n"
    "- hass.states.is_state('light.bedroom', 'on') returns a bool.\n"
    "- State objects expose: entity_id, domain, object_id, name, state, "
    "attributes, last_changed (ISO string), last_updated (ISO string), "
    "last_reported (ISO string or None), context.\n"
    "\n"
    "## Reading registries\n"
    "Choose one registry access style and do not mix them:\n"
    "- Instance style (simplest): use the pre-bound registry instances directly, "
    "for example device_registry.async_get('<device_id>').\n"
    "- Module style: call async_get(hass) only on er/dr/ar/fr, for example "
    "dr.async_get(hass).async_get('<device_id>').\n"
    "- Wrong: device_registry.async_get(hass). The global device_registry is "
    "already an instance, and async_get on it expects a device_id string.\n"
    "- list(entity_registry.entities.values()) lists all entity registry entries.\n"
    "- list(device_registry.devices.values()) lists all device entries.\n"
    "- er.async_entries_for_area(er.async_get(hass), area_id) returns entity "
    "entries in an area. Effective area = entity.area_id or device.area_id.\n"
    "- er.async_entries_for_device(er.async_get(hass), device_id) returns "
    "entity entries for a device.\n"
    "- er.async_entries_for_label(er.async_get(hass), label_id) returns entity "
    "entries with a label.\n"
    "- er.async_get_entity(er.async_get(hass), domain, platform, unique_id) "
    "returns the matching entity_id or None.\n"
    "- er.async_entries(er.async_get(hass)) returns all entity registry entries.\n"
    "- dr.async_entries_for_area(dr.async_get(hass), area_id) returns devices "
    "in an area.\n"
    "- dr.async_entries_for_label(dr.async_get(hass), label_id) returns "
    "devices with a label.\n"
    "- area_registry.async_get_area_by_name('Bedroom') returns the matching "
    "area (by name or alias) or None.\n"
    "- area_registry.async_list_areas() returns area entries.\n"
    "- Area objects expose: id, name, aliases, floor_id, labels, icon, "
    "picture, humidity_entity_id, temperature_entity_id.\n"
    "- Use area.id as the area_id argument for er/dr area lookup helpers.\n"
    "- floor_registry.async_get_floor_by_name('Ground Floor') returns the "
    "matching floor or None.\n"
    "- floor_registry.async_list_floors() returns floor entries.\n"
    "- Floor objects expose: floor_id, name, aliases, level, icon, created_at, "
    "modified_at.\n"
    "\n"
    "## Service calls\n"
    "- hass.services.has_service('light', 'turn_on') checks if a service exists.\n"
    "- hass.services.async_services() returns this metadata shape for all "
    "domains.\n"
    "- hass.services.async_services_for_domain('light') returns one domain's "
    "per-service metadata: supports_response (none, optional, or only), fields "
    "(a list of {name, required, type_hint, description} parameter briefs), "
    "and dynamic (bool; when true, listed fields are non-exhaustive). It "
    "returns {} for an unknown domain.\n"
    "- hass.services.supports_response('light', 'turn_on') returns response-mode "
    "metadata (none, optional, or only); it is not a service-existence check.\n"
    "- await hass.services.async_call('light', 'turn_on', "
    "{'brightness_pct': 80}, target={'entity_id': 'light.bedroom'}) performs "
    "the service call for real. Keep service data and target separate; put "
    "entities in target={'entity_id': ...}.\n"
    "- blocking=True waits for completion. blocking=False is fire-and-forget "
    "and yields no result and no detailed outcome error, so prefer blocking "
    "when you need to know whether the action succeeded.\n"
    "- return_response=True is required for services that produce a response, "
    "returns the response dict, and requires blocking=True.\n"
    "- The frozen snapshot is taken before actions run. A follow-up read in the "
    "same execute_home_code call will not reflect the change; call "
    "execute_home_code again to observe new state.\n"
    "- Actions apply sequentially with no rollback. If a later call fails, "
    "earlier calls have already happened.\n"
    "- Service-call errors are captured as helper_error with failed-call "
    "details. If the service name is wrong, the response includes valid "
    "services for that domain with brief parameter schemas; correct and retry.\n"
    "- async_call costs one helper call. Reads cost zero; respect the budget.\n"
    "\n"
    "## Execution rules\n"
    "- Assign the final answer to result, or end the code with a bare expression "
    "to have it promoted automatically.\n"
    "- print() output is captured into the printed field.\n"
    "- Keep code self-contained. Use the pre-bound globals and plain Python "
    "loops/comprehensions instead of importing helpers.\n"
    "- Standard builtins are available, including len, sum, min, max, sorted, "
    "dict, list, set, tuple, enumerate, zip, round, range, abs, any, all, map, "
    "filter, int, float, str, bool, and bytes.\n"
    "- Imports are limited. json, math, and re work for basic data handling; "
    "avoid other stdlib modules unless already proven necessary.\n"
    "- Do not import collections. Counter/defaultdict are unavailable; count "
    "with a dict loop like counts[key] = counts.get(key, 0) + 1.\n"
    "- Avoid filesystem, network, OS/process, pathlib/open, and current-time "
    "calls such as datetime.now() or date.today(). View timestamps are ISO "
    "strings; compare those strings directly when possible.\n"
    "- Reflection/introspection builtins are partially unavailable: dir, vars, "
    "setattr, and delattr are not available in the sandbox.\n"
    "- The live hass object, event bus, config, auth, filesystem, network, and "
    "OS/process APIs are not exposed.\n"
)


ACTIONS_DISABLED_PROMPT = (
    "## Service calls (disabled)\n"
    "Service calls are disabled for this assistant. Do not call "
    "hass.services.async_call; it will be rejected. Read states and "
    "registries only.\n"
)


EXECUTE_HOME_CODE_OUTPUT = (
    "Returns {execution, output, printed, actions}. execution.status "
    "is ok, code_error, helper_error, or setup_error. Use output only when "
    "status is ok. printed holds captured print() lines. actions lists "
    "service calls from hass.services.async_call with status, response, and "
    "error details."
)


def build_execute_home_code_description() -> str:
    """Return the execute_home_code tool description."""
    return "\n".join(
        [
            "Execute bounded Python/Monty code against a frozen read-only Home Assistant view.",
            "Read states and registries using native Home Assistant API patterns.",
            "Perform service calls via hass.services.async_call with structured action results.",
            EXECUTE_HOME_CODE_OUTPUT,
        ]
    )
